name: MRSZYMON-T1
favicon: null
layout_spectrum: 0.1468465921934694
typography_spectrum: 0.19447989715263247
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6509539510589093
  lightness: 0.6797765649389476
  saturation: 0.5052961150649935
  rhythmicContrast: 0.44140755175612867
purpose: []
